name: "Bambu P1 Streamer"
slug: "bambu_p1_camera_streamer"
version: "0.1.4"
description: " Expose the built-in camera of Bambu Lab P1S / P1P printers as a video stream for Home Assistant. Designed for print monitoring (view-only), Frigate / go2rtc integration and TV display. Detection is not supported."
arch:
  - amd64
startup: services
boot: auto
host_network: true
options:
  printer_address: ""
  printer_access_code: ""
schema:
  printer_address: str
  printer_access_code: password
